/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author sebas
 */
public class frmEleccionAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmEleccionAdmin
     */
    public frmEleccionAdmin() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgencias = new javax.swing.JLabel();
        lblSelecciona = new javax.swing.JLabel();
        lblCoche = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAgencias.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        lblAgencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgencias.setText("MENU");
        lblAgencias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblAgencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 145, -1));

        lblSelecciona.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblSelecciona.setText("Selecciona una opción:");
        getContentPane().add(lblSelecciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        lblCoche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-configuración-del-administrador-96.png"))); // NOI18N
        lblCoche.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCoche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCocheMouseClicked(evt);
            }
        });
        getContentPane().add(lblCoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 112, 116));

        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-usuario-90.png"))); // NOI18N
        lblCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCliente.setPreferredSize(new java.awt.Dimension(96, 96));
        lblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClienteMouseClicked(evt);
            }
        });
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 113, 116));

        lbl1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Coche");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 112, -1));

        lbl2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Cliente");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 113, -1));

        btnClose.setText("Cerrar");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Wallpaper.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCocheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCocheMouseClicked
        this.setVisible(false);
        mdiAdministradorCoche mde = new mdiAdministradorCoche();
        mde.setVisible(true);
    }//GEN-LAST:event_lblCocheMouseClicked

    private void lblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClienteMouseClicked
        this.setVisible(false);
        mdiAdministradorCliente mdc = new mdiAdministradorCliente();
        mdc.setVisible(true);
    }//GEN-LAST:event_lblClienteMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.setVisible(false);
        frmLogin logine = new frmLogin();
        logine.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEleccionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEleccionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEleccionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEleccionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEleccionAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblAgencias;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCoche;
    private javax.swing.JLabel lblSelecciona;
    // End of variables declaration//GEN-END:variables
}
