/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import SQL.Administrador;

/**
 *
 * @author sebas
 */
public class ifrmModificarCoche extends javax.swing.JInternalFrame {
Administrador admin3 = new Administrador();
    /**
     * Creates new form ifrmModificarCoche
     */
    public ifrmModificarCoche() {
        initComponents();
        admin3.cargarCoche(cmbMatricula);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdAgencia = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        lblIdAgencia = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblAnio = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        lblIdGarage = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtIdGarage = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        cmbMatricula = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtIdAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 191, -1));

        lblColor.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblColor.setText("Color:");
        getContentPane().add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });
        getContentPane().add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 83, -1));

        lblIdAgencia.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblIdAgencia.setText("Id Agencia:");
        getContentPane().add(lblIdAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 131, -1));

        lblAnio.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblAnio.setText("Año:");
        getContentPane().add(lblAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 80, -1));

        lblPrecio.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblPrecio.setText("Precio:");
        getContentPane().add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        btnActualizar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        lblIdGarage.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblIdGarage.setText("Id Garage:");
        getContentPane().add(lblIdGarage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        lblMatricula.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblMatricula.setText("Matricula:");
        getContentPane().add(lblMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 69, -1));

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 191, -1));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 191, -1));

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 191, -1));

        lblModelo.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblModelo.setText("Modelo:");
        getContentPane().add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        getContentPane().add(txtIdGarage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 55, -1));

        lblMarca.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblMarca.setText("Marca:");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        btnConsultar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        getContentPane().add(cmbMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 191, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EditarCoches.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 430, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EncabezadoAgregarPersonas.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(440, 604));
        jLabel2.setPreferredSize(new java.awt.Dimension(440, 604));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
          admin3.actualizarCoche(cmbMatricula, txtIdAgencia, txtIdGarage, txtModelo, txtColor, txtAnio, txtMarca, txtPrecio); // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        admin3.consultarVehiculo(cmbMatricula, txtIdAgencia, txtIdGarage, txtModelo, txtColor, txtAnio, txtMarca, txtPrecio);// TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JComboBox<String> cmbMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblIdAgencia;
    private javax.swing.JLabel lblIdGarage;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtIdAgencia;
    private javax.swing.JTextField txtIdGarage;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
