/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import SQL.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Det-Pc
 */
public class ifrmMostrarReservas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmMostrarReservas
     */
    Usuario user = new Usuario();

    public ifrmMostrarReservas() {
        initComponents();
        user.completarReservar(tblReservas, UsuarioDatos.cedula);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMATRICULA = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        btnFinalizar = new javax.swing.JButton();
        txtSeleccion1 = new javax.swing.JTextField();
        txtID1 = new javax.swing.JTextField();

        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Tus reservas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Vehiculo reservado seleccionado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 180, 20));

        txtMATRICULA.setEditable(false);
        txtMATRICULA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMATRICULA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMATRICULAMouseClicked(evt);
            }
        });
        getContentPane().add(txtMATRICULA, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 80, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setEnabled(false);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 130, -1));

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Color", "Matricula", "Fecha Inicio", "Fecha Final", "Precio x dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReservas.setColumnSelectionAllowed(true);
        tblReservas.getTableHeader().setReorderingAllowed(false);
        tblReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReservas);
        tblReservas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblReservas.getColumnModel().getColumnCount() > 0) {
            tblReservas.getColumnModel().getColumn(0).setResizable(false);
            tblReservas.getColumnModel().getColumn(1).setResizable(false);
            tblReservas.getColumnModel().getColumn(2).setResizable(false);
            tblReservas.getColumnModel().getColumn(3).setResizable(false);
            tblReservas.getColumnModel().getColumn(4).setResizable(false);
            tblReservas.getColumnModel().getColumn(5).setResizable(false);
            tblReservas.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 640, 280));

        btnFinalizar.setText("Finalizar reservas");
        btnFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarMouseClicked(evt);
            }
        });
        getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 130, -1));

        txtSeleccion1.setEditable(false);
        txtSeleccion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSeleccion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSeleccion1MouseClicked(evt);
            }
        });
        getContentPane().add(txtSeleccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 160, -1));

        txtID1.setEditable(false);
        txtID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtID1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtID1MouseClicked(evt);
            }
        });
        getContentPane().add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 60, -1));

        setBounds(125, 80, 706, 475);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        int seleccionar = tblReservas.rowAtPoint(evt.getPoint());
        user.eliminarReserva(UsuarioDatos.cedula, txtMATRICULA.getText(), txtID1.getText());
        user.completarReservar(tblReservas, UsuarioDatos.cedula);
        txtID1.setText(" ");
        txtMATRICULA.setText(" ");
        txtSeleccion1.setText(" ");

    }//GEN-LAST:event_btnEliminarMouseClicked

    private double calcularTotal() {

        double total = 0;
        int days;
        double precio;
        for (int i = 0; i < tblReservas.getRowCount(); i++) {

            LocalDate fechaInicial = LocalDate.parse(String.valueOf(tblReservas.getValueAt(i, 5)));
            LocalDate FechaFinal = LocalDate.parse(String.valueOf(tblReservas.getValueAt(i, 6)));
            Duration dias = Duration.between(fechaInicial.atStartOfDay(), FechaFinal.atStartOfDay());
            System.out.println("dias = " + dias.toDays());
            days = (int) dias.toDays();
            precio = (Double.parseDouble(String.valueOf(tblReservas.getValueAt(i, 7))));
            System.out.println(precio);
            total += days*precio;
            System.out.println(total);
        }
        return total;
    }

    private void txtMATRICULAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMATRICULAMouseClicked

    }//GEN-LAST:event_txtMATRICULAMouseClicked

    private void tblReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservasMouseClicked
        int seleccionar = tblReservas.rowAtPoint(evt.getPoint());
        txtSeleccion1.setText(String.valueOf(tblReservas.getValueAt(seleccionar, 1)) + " " + String.valueOf(tblReservas.getValueAt(seleccionar, 2)));
        txtID1.setText(String.valueOf(tblReservas.getValueAt(seleccionar, 0)));
        txtMATRICULA.setText(String.valueOf(tblReservas.getValueAt(seleccionar, 4)));

        btnEliminar.setEnabled(true);    }//GEN-LAST:event_tblReservasMouseClicked

    private void txtSeleccion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSeleccion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeleccion1MouseClicked

    private void txtID1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtID1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID1MouseClicked

    private void btnFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarMouseClicked
        calcularTotal();
    }//GEN-LAST:event_btnFinalizarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtMATRICULA;
    private javax.swing.JTextField txtSeleccion1;
    // End of variables declaration//GEN-END:variables
}
