/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import SQL.Administrador;

/**
 *
 * @author sebas
 */
public class ifrmAgregarCliente extends javax.swing.JInternalFrame {
Administrador admin1 = new Administrador();
    /**
     * Creates new form ifrmAgregarCliente
     */
    public ifrmAgregarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFecha = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        txtNacion = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblNacion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txtCedu = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(459, 603));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 398, 191, -1));

        lblSexo.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblSexo.setText("Sexo:");
        getContentPane().add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 291, -1, -1));
        getContentPane().add(txtNacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 438, 191, -1));

        lblFecha.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblFecha.setText("Fecha de nacimiento:");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 401, -1, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 475, 191, -1));

        lblNacion.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblNacion.setText("Nacionalidad:");
        getContentPane().add(lblNacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 438, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblTelefono.setText("Telefono:");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 482, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 526, -1, -1));

        lblEstado.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblEstado.setText("Estado Civil:");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 368, -1, -1));

        lblCedula.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblCedula.setText("Cedula de identidad:");
        getContentPane().add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 184, 142, -1));
        getContentPane().add(txtCedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 180, 186, -1));
        getContentPane().add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 287, 186, -1));
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 217, 186, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 247, 186, -1));

        lblNombre.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 221, -1, -1));
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 364, 191, -1));

        lblApellido.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblApellido.setText("Apellido:");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 251, -1, -1));

        lblEdad.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblEdad.setText("Edad:");
        getContentPane().add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 331, -1, -1));
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 327, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblDireccion.setText("Direccion:");
        getContentPane().add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 144, -1, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 140, 134, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UserAdd.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EncabezadoAgregarPersonas.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2090, 1120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
           admin1.agregarCliente(txtCedu, txtNom, txtApellido, txtEdad, txtSexo, txtDireccion, txtTelefono, txtFecha, txtEstado, txtNacion); // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNacion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedu;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNacion;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
