/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import SQL.Administrador;

/**
 *
 * @author sebas
 */
public class ifrmModificarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmModificarCliente
     */
    Administrador admin2 = new Administrador ();
    public ifrmModificarCliente() {
        initComponents();
        admin2.cargarCliente(cmbCI);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActualizar = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        lblDirec = new javax.swing.JLabel();
        txtdirec = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtNacion = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblcedula = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        lblNacion = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        btnConsul = new javax.swing.JButton();
        lblTelefono = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbCI = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        btnActualizar1 = new javax.swing.JButton();
        lblEstado1 = new javax.swing.JLabel();
        lblDirec1 = new javax.swing.JLabel();
        txtdirec1 = new javax.swing.JTextField();
        txtFecha1 = new javax.swing.JTextField();
        txtSexo1 = new javax.swing.JTextField();
        lblEdad1 = new javax.swing.JLabel();
        lblSexo1 = new javax.swing.JLabel();
        txtNom1 = new javax.swing.JTextField();
        txtEdad1 = new javax.swing.JTextField();
        txtNacion1 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        lblcedula1 = new javax.swing.JLabel();
        lblFecha1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        txtEstado1 = new javax.swing.JTextField();
        lblNacion1 = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        btnConsul1 = new javax.swing.JButton();
        lblTelefono1 = new javax.swing.JLabel();
        cmbCI1 = new javax.swing.JComboBox<>();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        lblEstado.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblEstado.setText("Estado Civil:");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        lblDirec.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblDirec.setText("Direccion:");
        getContentPane().add(lblDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 142, -1));
        getContentPane().add(txtdirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 186, -1));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 191, -1));
        getContentPane().add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        lblEdad.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblEdad.setText("Edad:");
        getContentPane().add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        lblSexo.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblSexo.setText("Sexo:");
        getContentPane().add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));
        getContentPane().add(txtNacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 191, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        lblcedula.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblcedula.setText("Cedula de identidad:");
        getContentPane().add(lblcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lblFecha.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblFecha.setText("Fecha de nacimiento:");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        lblNombre.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 191, -1));
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 191, -1));

        lblNacion.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblNacion.setText("Nacionalidad:");
        getContentPane().add(lblNacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        lblApellido.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblApellido.setText("Apellido:");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        btnConsul.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btnConsul.setText("Consultar");
        btnConsul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsulMouseClicked(evt);
            }
        });
        getContentPane().add(btnConsul, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblTelefono.setText("Telefono:");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EditarUsuario.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 450, -1));

        getContentPane().add(cmbCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 186, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EncabezadoAgregarPersonas.png"))); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(465, 603));
        jLabel2.setPreferredSize(new java.awt.Dimension(465, 603));
        jLabel2.setRequestFocusEnabled(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 2090, 1120));

        jInternalFrame1.setClosable(true);

        btnActualizar1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btnActualizar1.setText("Actualizar");
        btnActualizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizar1MouseClicked(evt);
            }
        });

        lblEstado1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblEstado1.setText("Estado Civil:");

        lblDirec1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblDirec1.setText("Direccion:");

        lblEdad1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblEdad1.setText("Edad:");

        lblSexo1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblSexo1.setText("Sexo:");

        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });

        lblcedula1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblcedula1.setText("Cedula de identidad:");

        lblFecha1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblFecha1.setText("Fecha de nacimiento:");

        lblNombre1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblNombre1.setText("Nombre:");

        lblNacion1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblNacion1.setText("Nacionalidad:");

        lblApellido1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblApellido1.setText("Apellido:");

        btnConsul1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btnConsul1.setText("Consultar");
        btnConsul1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsul1MouseClicked(evt);
            }
        });

        lblTelefono1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblTelefono1.setText("Telefono:");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTelefono1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsul1)
                .addGap(43, 43, 43)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdirec1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(btnActualizar1)
                    .addComponent(cmbCI1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEstado1)
                                .addComponent(lblFecha1)
                                .addComponent(lblNacion1))
                            .addGap(46, 46, 46)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEstado1)
                                .addComponent(txtFecha1)
                                .addComponent(txtNacion1)
                                .addComponent(txtTelefono1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)))
                        .addComponent(lblSexo1)
                        .addComponent(lblEdad1)
                        .addComponent(lblApellido1)
                        .addComponent(lblNombre1)
                        .addComponent(lblDirec1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblcedula1))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(cmbCI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtdirec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTelefono1)
                .addGap(57, 57, 57)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar1)
                    .addComponent(btnConsul1))
                .addGap(31, 31, 31))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(lblcedula1)
                    .addGap(18, 18, 18)
                    .addComponent(lblDirec1)
                    .addGap(22, 22, 22)
                    .addComponent(lblNombre1)
                    .addGap(15, 15, 15)
                    .addComponent(lblApellido1)
                    .addGap(25, 25, 25)
                    .addComponent(lblSexo1)
                    .addGap(18, 18, 18)
                    .addComponent(lblEdad1)
                    .addGap(18, 18, 18)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(lblEstado1)
                            .addGap(18, 18, 18)
                            .addComponent(lblFecha1))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(txtEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNacion1))
                    .addGap(15, 15, 15)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 283, 0, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnConsulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsulMouseClicked
        admin2.consultaCliente(txtNom, txtApellido, txtTelefono, txtdirec, txtFecha, cmbCI, txtEstado, txtNacion, txtSexo, txtEdad);// TODO add your handling code here:
    }//GEN-LAST:event_btnConsulMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
     admin2.actualizarCliente(cmbCI, txtNom, txtApellido, txtEdad, txtSexo, txtdirec, txtTelefono, txtFecha, txtEstado, txtNacion);        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnActualizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar1MouseClicked

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1ActionPerformed

    private void btnConsul1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsul1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsul1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnConsul;
    private javax.swing.JButton btnConsul1;
    private javax.swing.JComboBox<String> cmbCI;
    private javax.swing.JComboBox<String> cmbCI1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblDirec;
    private javax.swing.JLabel lblDirec1;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEdad1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblNacion;
    private javax.swing.JLabel lblNacion1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSexo1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblcedula1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEdad1;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstado1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFecha1;
    private javax.swing.JTextField txtNacion;
    private javax.swing.JTextField txtNacion1;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNom1;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtSexo1;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtdirec;
    private javax.swing.JTextField txtdirec1;
    // End of variables declaration//GEN-END:variables
}
