/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package GUI;

import java.awt.Dimension;

/**
 *
 * @author sebas
 */
public class mdiAdministradorCoche extends javax.swing.JFrame {

    /**
     * Creates new form mdiAdministrador
     */
    
    public mdiAdministradorCoche() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Escritorio = new javax.swing.JDesktopPane();
        lblFlecha = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuAgregar = new javax.swing.JMenu();
        mnuActualizar = new javax.swing.JMenu();
        mnuConsulta2 = new javax.swing.JMenu();
        mnuCerrar = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar5.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar5.add(jMenu11);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFlecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFlecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-izquierda-círculo-60.png"))); // NOI18N
        lblFlecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFlecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFlechaMouseClicked(evt);
            }
        });
        Escritorio.add(lblFlecha);
        lblFlecha.setBounds(10, 10, 60, 60);

        menuBar.setPreferredSize(new java.awt.Dimension(500, 40));

        mnuAgregar.setMnemonic('f');
        mnuAgregar.setText("Agregrar");
        mnuAgregar.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        mnuAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAgregarMouseClicked(evt);
            }
        });
        menuBar.add(mnuAgregar);

        mnuActualizar.setText("Modificar");
        mnuActualizar.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        mnuActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuActualizarMouseClicked(evt);
            }
        });
        menuBar.add(mnuActualizar);

        mnuConsulta2.setMnemonic('e');
        mnuConsulta2.setText("Consultar");
        mnuConsulta2.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        mnuConsulta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuConsulta2MouseClicked(evt);
            }
        });
        mnuConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsulta2ActionPerformed(evt);
            }
        });
        menuBar.add(mnuConsulta2);

        mnuCerrar.setMnemonic('h');
        mnuCerrar.setText("Cerrar sesion");
        mnuCerrar.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        mnuCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCerrarMouseClicked(evt);
            }
        });
        mnuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarActionPerformed(evt);
            }
        });
        menuBar.add(mnuCerrar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_mnuCerrarActionPerformed

    private void mnuCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCerrarMouseClicked
       this.setVisible(false);
        frmLogin login = new frmLogin();
        login.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_mnuCerrarMouseClicked

    private void mnuConsulta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuConsulta2MouseClicked
        
        ifrmConsultarVehiculos   vehiculo1 = new ifrmConsultarVehiculos();
        Escritorio.add(vehiculo1);
        Dimension escritor = Escritorio.getSize();
        Dimension frame = vehiculo1.getSize();
        vehiculo1.setLocation((escritor.width - frame.width)/2, (escritor.height - frame.height)/2);
        vehiculo1.show();
        vehiculo1.toFront();
    }//GEN-LAST:event_mnuConsulta2MouseClicked

    private void mnuAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAgregarMouseClicked
       ifrmAgregarCoche agregar = new ifrmAgregarCoche();     
       Escritorio.add(agregar);
       Dimension escritor = Escritorio.getSize();
        Dimension frame = agregar.getSize();
        agregar.setLocation((escritor.width - frame.width)/2, (escritor.height - frame.height)/2);
       agregar.toFront();
       agregar.show();
 
// TODO add your handling code here:

    }//GEN-LAST:event_mnuAgregarMouseClicked

    private void lblFlechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFlechaMouseClicked
        this.setVisible(false);
        frmEleccionAdmin ad = new frmEleccionAdmin();
        ad.setVisible(true);
    }//GEN-LAST:event_lblFlechaMouseClicked

    private void mnuConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsulta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuConsulta2ActionPerformed

    private void mnuActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuActualizarMouseClicked
        
        
        
        ifrmModificarCoche mdrc = new ifrmModificarCoche();
        Escritorio.add(mdrc);
        Dimension escritor = Escritorio.getSize();
        Dimension frame = mdrc.getSize();
        mdrc.setLocation((escritor.width - frame.width)/2, (escritor.height - frame.height)/2);
        mdrc.show();
        mdrc.toFront();  
        
        
        
        
         
// TODO add your handling code here:
    }//GEN-LAST:event_mnuActualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdiAdministradorCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdiAdministradorCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdiAdministradorCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiAdministradorCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiAdministradorCoche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblFlecha;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuActualizar;
    private javax.swing.JMenu mnuAgregar;
    private javax.swing.JMenu mnuCerrar;
    private javax.swing.JMenu mnuConsulta2;
    // End of variables declaration//GEN-END:variables

}
