/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Desktop;

/**
 *
 * @author Det-Pc
 */
public class mdiInvitado extends javax.swing.JFrame {

    /**
     * Creates new form mdiInvitado
     */
    public mdiInvitado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMostrar = new javax.swing.JMenu();
        mnuCerrar2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(195, 40));

        mnuMostrar.setText("Mostrar Vehiculos");
        mnuMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuMostrar.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        mnuMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMostrarMouseClicked(evt);
            }
        });
        mnuMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMostrarActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuMostrar);

        mnuCerrar2.setText("Cerrar sesion");
        mnuCerrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuCerrar2.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        mnuCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCerrar2MouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuCerrar2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCerrar2MouseClicked
        this.setVisible(false);
        frmLogin login = new frmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_mnuCerrar2MouseClicked

    private void mnuMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMostrarMouseClicked
        ifrmMostrarVehiculos vehiculo = new ifrmMostrarVehiculos();
        Escritorio.add(vehiculo);
        vehiculo.show();
        vehiculo.toFront();

    }//GEN-LAST:event_mnuMostrarMouseClicked

    private void mnuMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMostrarActionPerformed
        ifrmMostrarVehiculos vehiculo = new ifrmMostrarVehiculos();
        Escritorio.add(vehiculo);
        vehiculo.show();
        vehiculo.toFront();


    }//GEN-LAST:event_mnuMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdiInvitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdiInvitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdiInvitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiInvitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiInvitado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuCerrar2;
    public javax.swing.JMenu mnuMostrar;
    // End of variables declaration//GEN-END:variables
}
